name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - src/**
      - versions/**
      - build.gradle
      - gradle.properties
      - settings.gradle
  push:
    branches:
      - master
      - dev
    paths:
      - src/**
      - versions/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    env:
      CI_BUILD: true
      RUNNER_DISABLE_IPV6: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 25

      - name: Validate Gradle Wrapper
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_wait_seconds: 10
          timeout_minutes: 5
          polling_interval_seconds: 5
          command: |
                      uses: gradle/actions/wrapper-validation@v3

      - name: Make Gradle Wrapper Executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build --stacktrace